### ISSUE TITLE
@autorelease pool for NSError allocation may be causing EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by ianterrell** [mhausherr/Light-Untar-for-iOS#10]
When we pass an NSError** into createFilesAndDirectoriesAtPath:withTarObject:size:error:, we get an EXC_BAD_ACCESS coming out of it. It looks like the @autorelease pool created on L103 drains and releases the memory. Passing in nil is fine for us.

**Comment by mhausherr** [comment]
Fixed in 0.3.0
