### ISSUE TITLE
Unsupported 'L' block type

### ISSUE THREAD

**Issue by vittoriom** [mhausherr/Light-Untar-for-iOS#20]
It looks like a block with type 'L' indicates a long filename.

```
HEADER type 'L'
BLOCKS of data with the real long filename
```

I have this issue where a .tgz file has a 'L'-type block and the uncompressing just stops there. 
I will have a look into the implementation to see whether it's a fix I can apply myself. In that case I will open a PR.

**Comment by fabianfett** [comment]
You mean like that?!
https://github.com/fabianfett/Light-Untar-for-iOS/blob/master/NSFileManager%2BTar.m

**Comment by vittoriom** [comment]
Well, that's quite cool :blush: You should open a PR! 

Thanks mate :thumbsup:

**Comment by iori57** [comment]
I'm having the same issue now, is this fixed? The link provided by fabianfett is broken..
